---
vagrantfile-local:
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: ''
        memory: '1024'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.110
            forwarded_port:
                Cy8zhxjtb4mh:
                    host: '8000'
                    guest: '80'
                pHqehpPoDZL1:
                    host: '33060'
                    guest: '3306'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            IyPgSu0ncrN3:
                owner: www-data
                group: www-data
                source: ./assets/
                target: /var/www/assets/
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'false'
            Fl2mbjzmOims:
                owner: www-data
                group: www-data
                source: /projects/node/phpstorm/example/api/
                target: /var/www/api/
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'false'
            YnNjje07B8Gu:
                owner: www-data
                group: www-data
                source: ./assets/secured_files/
                target: /media/NAS/www/secured_files/
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - curl
        - htop
        - nano
        - proftpd
        - postfix
        - wget
        - telnet
        - vim-common
users_groups:
    install: '1'
    groups:
        - developers
    users:
        - 'developer:developers'
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules:
        wrbavOFIomJO:
            port:
                - '21'
                - '22'
                - '25'
                - '80'
                - '1025'
                - '1080'
                - '3306'
            priority: '100'
            proto: tcp
            action: accept
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - cache
        - dav
        - dav_fs
        - deflate
        - headers
        - info
        - ldap
        - mime_magic
        - rewrite
        - ssl
        - userdir
        - vhost_alias
    vhosts:
        rethinkgroup:
            servername: api.rethinkgroup.org
            serveraliases:
                - www.api.rethinkgroup.org
            docroot: /var/www/api
            port: '443'
            setenv:
                - 'APP_ENV dev'
            directories:
                dztq0xlbbngg:
                    provider: directory
                    path: /var/www/api
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl: '1'
            ssl_cert: '/var/www/assets/keys/cert.crt'
            ssl_key: '/var/www/assets/keys/cert.key'
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        sq98vhzlqff9:
            proxy: ''
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '54'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - devel
            - gd
            - intl
            - mbstring
            - mcrypt
            - mysqlnd
        pear: {  }
        pecl:
            - pecl_http
            - mysql
            - mysqlnd_ms
            - mysqlnd_qc
            - tidy
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: America/New_York
    mod_php: '1'
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '0'
    versions:
        pmTqgheFAfmX:
            default: '1'
            version: 1.9.3
            gems:
                - rails
            bundler: '1'
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions:
        LfoNk3hBucl8:
            version: ''
mysql:
    install: '1'
    override_options: {  }
    root_password: root
    adminer: '1'
    databases:
        sVc310wPWbqg:
            grant:
                - ALL
            name: orange
            host: localhost
            user: jbrayton
            password: 'rethink this!'
            sql_file: ''
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '1'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'

